import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-multi-choice-test',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './multi-choice-test.component.html',
  styleUrls: ['./multi-choice-test.component.css']
})
export class MultiChoiceTestComponent implements OnInit {
  // Embedded TSV (header + a few sample rows). Replace or extend with the full dataset if desired.
    // Embedded TSV (header + a few sample rows). You can add three optional distractor columns
    // named Distractor1, Distractor2, Distractor3 (or any header containing 'distractor').
    // Replace or extend with the full dataset if desired.
  private rawTsv = `Thématique	Notions	Connaisance	Question	Reponse	Distracteur 1	Distracteur 2	Distracteur 3
Principes et valeurs de la République	Devise et symboles de la République	Connaitre et comprendre la République	Qu'est-ce que c'est une republique?	Un mode d'organisation des pouvoirs	Une forme de monarchie parlementaire	Une communauté fondée sur une ethnie unique	Un système où un seul homme détient tous les pouvoirs
Principes et valeurs de la République	Devise et symboles de la République	Connaitre et comprendre la République	Que dit l'art. 1er de la Constitution de l'unité et indivisibilité de la République?	« La France est une République indivisible, laïque, démocratique et sociale »	« La France est une monarchie constitutionnelle, tolérante, sociale et unie »	« La France est une nation unie, respectueuse des traditions et de l'histoire »	« La France est une démocratie libérale, unie et décentralisée »
Principes et valeurs de la République	Devise et symboles de la République	Connaitre et comprendre la République	Que dit l'art. 3 de la Constitution de la souveraineté nationale?	« La souveraineté nationale appartient au peuple qui l'exerce par ses représentants et par la voie du référendum »	« La souveraineté nationale appartient au chef de l'État qui l'exerce par décret »	« La souveraineté est déléguée aux représentants élus pour une durée illimitée »	« La souveraineté est partagée entre le Parlement, le gouvernement et le peuple »
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : liberté	Quel est le sens de la liberté?	Respecter les autres dans leur intégrité et leur diversité, respecter la diversité des croyances et des convictions	Faire tout ce que l'on veut tant que ça ne nuit pas à autrui	L'absence totale de contrainte et de loi	La possibilité de choisir son gouvernement et ses représentants
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : liberté	Quelles sont les différents types de libertés individuelles et collectives?	Liberté de pensée, d'opinion, d'expression, de religion, de travail, de circulation, de réunion et d'association, de choix sexuels et de mariage (interdiction de la polygamie : principe et conséquences) ;	Liberté d'entreprendre, de manifester, de vote et d'accès à la propriété	Liberté de culte, de circulation, de défense nationale et d'instruction publique	Liberté de la presse, de la chasse, d'importation et d'exportation
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : liberté	Quelles sont les différentes formes d'engagement dans la vie associative et locale?	Droit de créer et d'adhérer à une association, droit syndical.	L'obligation de faire le service militaire	Le droit de se présenter à toutes les élections à partir de 16 ans	Le droit de manifester avec des armes
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Quel est le sens de l'égalité?	égalité des droits et des devoirs, égalité entre les femmes et les hommes, accès aux droits fondamentaux, égalité devant la loi	Le fait que tout le monde ait exactement les mêmes biens et revenus	Le fait de permettre aux citoyens de choisir leur niveau d'imposition	Le fait que seules les personnes nées en France aient les mêmes droits
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Que signifie respecter les droits d'autrui et accepter les différences?	Lutte contre les discriminations, le racisme, l'antisémitisme et la haine anti-LGBT.	Le fait de favoriser uniquement sa communauté d'origine	L'interdiction de toute critique envers les autorités	La promotion d'une seule ethnie et culture nationale
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Quel est le sens de la fraternité ?	comprendre la valeur de fraternité comme la capacité à voir en autrui un semblable, malgré les différences. C'est pourquoi la fraternité républicaine est une fraternité civique, et non pas ethnique ou religieuse.	Le fait de favoriser uniquement ses proches et sa famille	La liberté totale de ne pas aider les personnes en difficulté	L'obligation de partager la même religion avec ses voisins
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Differentes formes de solidarité?	• Collective : le principe de solidarité signifie que la Nation assure aux individus libres et égaux en droit une protection. Remplir ses obligations fiscales est un acte solidaire qui permet de financer les services publics au bénéfice de tous ; le principe de solidarité exige aussi que chaque citoyen doive défendre la Nation en cas de danger ; • Intergénérationnelle : le principe de solidarité signifie le soutien entre différentes générations (exemple : retraites).	Uniquement l'aide entre membres d'une même communauté religieuse	L'obligation pour les jeunes de financer à 100% les retraites	Le droit de s'isoler et de refuser toute contribution collective
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Quel est le drapeau de la France?	Bleu, Blanc, Rouge (Le drapeau tricolore).	Vert, blanc, rouge	Bleu, jaune, rouge	Bleu, blanc, jaune
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Comment s'appele l'hymne?	La Marseillaise	Le Chant des Partisans	Le Temps des Cerises	L'Internationale
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Quelle est la devise de la France?	Liberté, Égalité, Fraternité	Honneur et Patrie	Travail, Famille, Patrie	Pour la France
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Qui est la Marianne?	Un symbole de la République française, représentant la Liberté et la Raison.	La femme du Président de la République	Une ancienne Reine de France	La sainte patronne de Paris
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Quuand est la fête nationale ?	14 juillet (prise de la Bastille)	Le 11 novembre	Le 8 mai	Le 1er mai
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Pourquoi le coq est le symbole de la France ?	L'association du coq et de la France est née d'un jeu de mot : le mot latin gallus signifie à la fois « gaulois » et « coq »	Parce qu'il est un animal craintif et humble	C'est un emblème choisi par Napoléon Ier	Il est le seul animal capable de voler très haut
Principes et valeurs de la République	Devise et symboles de la République	Savoir que le français est la langue nationale et officielle	Quel est la langue officielle de la republique?	« Le français est la langue de la République française » (article 2 de la Constitution).	Le latin	L'anglais et le français sont officiels	La langue régionale majoritaire
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Comment la France est devenue laïque?	La loi de 1905 est la conclusion de siècles de lutte entre les pouvoirs religieux et politiques en France. La laïcité n'est pas la négation des religions, elle organise les relations entre l'Etat et les religions	Par un décret du Roi Louis XIV au 17e siècle	Uniquement par une décision de Napoléon III	Grâce à une consultation populaire en 1999
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quel est le principe de liberté de conscience?	La laïcité garantit la liberté de conscience et l'égalité de tous les citoyens, quelles que soient leurs croyances ; la neutralité de l'État à l'égard des religions et le libre exercice des cultes (loi de 1905). La liberté de conscience est celle de croire, celle de ne pas croire et celle de ne plus croire, celle aussi de changer de croyance ou de religion (droit à l'apostasie et droit de se convertir). La liberté de conscience inclut le droit au blasphème. L'exercice de cette liberté peut être limité dans le respect des principes constitutionnels (ex. interdiction du prosélytisme abusif) ;	L'obligation pour l'État de financer toutes les croyances	Le droit de ne respecter aucune loi au nom de sa religion	Le fait que seul l'athéisme est autorisé
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quelle est la place des religions en France et le rôle de l'Etat face a elles?	Principe de séparation des Eglises et de l'Etat, principe de libre organisation des cultes. Principe de neutralité : l'Etat protège et sécurise les lieux de culte et lutte contre les actes antireligieux. L'Etat est garant de la liberté religieuse y compris dans les lieux de privation de liberté. L'Etat punit la pression forte sur une personne de croire ou de ne pas croire	L'État doit construire de nouveaux lieux de culte pour toutes les religions	L'État intervient directement dans l'organisation interne des cultes	L'État interdit toute pratique religieuse en public
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Que dit le principe de laïcité pour l'usager du service public?	Tous les usagers sont égaux devant le service public. Ils ont le droit d'exprimer leurs convictions religieuses dans la limite du respect de l'ordre public. Les usagers doivent s'abstenir de toute forme de prosélytisme. Le principe de laïcité interdit à quiconque de se prévaloir de ses croyances religieuses pour s'affranchir des règles communes (Voir Charte de la laïcité des usagers des services publics)	Les usagers du service public doivent être neutres et ne rien exprimer de leurs convictions	Ils peuvent exiger un traitement différent en fonction de leur religion	Ils doivent cacher tout signe d'appartenance religieuse dans l'espace public
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quel est le principe de laïcité au travail?	Chacun a le droit d'avoir ses croyances ou convictions. Dans les institutions publiques, les agents sont soumis au principe de neutralité. Dans le secteur privé, la liberté de manifester sa religion peut toutefois être restreinte pour des impératifs d'hygiène, de sécurité ou si son exercice empêche le bon déroulement de l'activité de l'entreprise ;	Les agents publics peuvent faire du prosélytisme sur leur lieu de travail	La religion est interdite dans toutes les entreprises privées	L'employeur est obligé de modifier les horaires de travail pour toutes les pratiques religieuses
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quel est le principe de laïcité à l'école publique?	La laïcité impose des règles à tous les membres de la communauté scolaire afin de protéger la liberté de choix de chaque enfant et préserver le fonctionnement de l'école. Il est interdit de choisir les enseignements en fonction de ses croyances religieuses (Voir Charte de la laïcité à l'école).	Les parents peuvent demander la suppression de certains cours (sciences, histoire) au nom de la religion	L'école publique est obligatoire pour tous les enfants, y compris les enfants d'immigrés	Les professeurs sont obligés d'enseigner la religion majoritaire
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Quel est le principe d'Etat de droit?	Système dans lequel la loi est au-dessus de tous : elle s'applique à toutes les personnes y compris les autorités publiques. Cela garantit que les droits et libertés de chacun sont protégés ;	Le gouvernement peut décider seul ce qui est loi	Le Président de la République est au-dessus de toutes les lois	Les lois sont faites uniquement par les juges
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Quels sont les trois pouvoirs?	législatif, exécutif, autorité judiciaire	Religieux, Militaire, Économique	Local, Régional, National	Éducatif, Sanitaire, Social
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Decrit le rôle des trois pouvoirs et les principaux acteurs	faire les lois (députés et sénateurs), appliquer les lois (gouvernement), rendre la justice (les juges) ;	faire les lois (le Président), appliquer les lois (les Préfets), rendre la justice (la Police)	faire les lois (les Maires), appliquer les lois (les Citoyens), rendre la justice (le Parlement)	faire les lois (le Conseil Constitutionnel), appliquer les lois (l'ONU), rendre la justice (la Cour d'Appel)
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Decrit le principe de la séparation des pouvoirs et sa mise en œuvre	Principe constitutionnel consacré par l'article 16 de la Déclaration des droits de l'homme et du citoyen qui établit un équilibre entre les pouvoirs : responsabilité du gouvernement devant le Parlement, pouvoirs du président de la République élu au suffrage universel direct, indépendance de la justice.	Le Président de la République cumule les trois pouvoirs pour plus d'efficacité	Le Parlement peut juger directement les citoyens et les condamner	Le pouvoir judiciaire est sous l'autorité du Premier ministre
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre le droit de vote et les élections	Quelles sont les conditions pour voter en France?	Avoir la nationalité française, être majeur, ne pas avoir été privé de ses droits civils et politiques suite à une condamnation	Être propriétaire d'un bien immobilier, avoir 25 ans et être né en France	Ne pas avoir de casier judiciaire, avoir 21 ans et résider en France depuis 10 ans	Être salarié d'une entreprise française et avoir une carte d'identité
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre le droit de vote et les élections	Que dit le principe de pluralité des partis?	Condition nécessaire de la démocratie, vise à assurer une représentation des différents courants d'expression socioculturels	Le gouvernement doit toujours être composé d'un seul parti politique	Seuls deux partis politiques majeurs sont autorisés	Les partis politiques doivent être financés uniquement par l'État
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le découpage administratif et institutionnel	Citez les trois niveaux de l'organisation territoriale de l'État.	Organisation territoriale en trois niveaux : la Commune, le Département, la Région. L'État est représenté par les préfectures de région et de département.	Les trois niveaux sont : le Canton, l'Arrondissement, la Circonscription	Les trois niveaux sont : l'Europe, l'État, la Commune	Les trois niveaux sont : l'Armée, la Police, les Impôts
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le découpage administratif et institutionnel	Quelles sont les principales institutions politiques de la Ve République?	• pouvoir exécutif : le président de la République, le gouvernement composé du Premier ministre et des ministres ; • pouvoir législatif : le Parlement composé de l'Assemblée nationale et du Sénat ; • pouvoir judicaire : les tribunaux (ordres judiciaire et administratif) ; • autres institutions : Conseil constitutionnel, Défenseur des droits, Banque de France.	Le Roi, la Couronne, les Ducs et les Seigneurs	Le Saint-Siège, l'Évêché, le Clergé	Le FMI, la Banque Mondiale, l'OTAN
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le fonctionnement démocratique	Decrit le rôle des acteurs politiques au niveau national et local	le président de la République, le Premier ministre, le maire ;	Le rôle des acteurs politiques est de juger les citoyens	Leur rôle est de diriger l'armée et de faire la guerre	Leur rôle est de nommer les fonctionnaires et d'attribuer les honneurs
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le fonctionnement démocratique	Quelles sont les différents types d'élections?	présidentielles, législatives, européennes, locales	Élection du Préfet, du Juge, du Général de l'armée	Élection du Pape, du Chef de la police, et du PDG de la SNCF	Élection des chefs d'entreprise et des directeurs d'école
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le fonctionnement démocratique	Quelle est la durée des principaux mandats électifs (Président, Députés, Maires) ?	Président de la République : 5 ans ; Députés : 5 ans ; Maires : 6 ans ; Sénateurs : 6 ans (renouvelés par moitié tous les 3 ans).	Président de la République : 7 ans ; Députés : 4 ans ; Maires : 3 ans	Tous les mandats sont de 4 ans renouvelables une fois	La durée des mandats est à vie ou jusqu'à la retraite
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaître et comprendre les fondements de l'Union européenne	Quelles sont les principales étapes historiques et le nombre actuel d'États membres de l'UE ?	L'UE a été fondée sur le Traité de Rome (1957) et compte actuellement 27 États membres.	L'UE a été fondée en 1989 après la chute du Mur de Berlin et compte 15 membres	L'UE a été fondée en 1945 après la Seconde Guerre mondiale et compte 50 membres	L'UE a été fondée sur l'Accord de Schengen (1995) et compte 10 membres
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaître et comprendre les fondements de l'Union européenne	Quels sont le drapeau et l'hymne de l'Union européenne?	Hymne: l'«Ode à la joie» de Beethoven, drapeau blueu avec un cercle conformé par 12 etoiles dorées.	Hymne: La Marseillaise, drapeau vert avec 27 étoiles	Hymne: God Save the Queen, drapeau rouge avec une croix	Hymne: L'Internationale, drapeau blanc avec un blason
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaitre et comprendre le fonctionnement de l'Union européenne	Quelles sont les institutions européennes ?	Parlement européen, Conseil de l'Union européenne, Commission européenne	Le FMI, l'OTAN, l'ONU	La Banque Mondiale, la CPI, la CJUE	Le Conseil de l'Europe, le Conseil Constitutionnel, la Cour de Cassation
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaitre et comprendre le fonctionnement de l'Union européenne	Quels sont les principes essentiels de l'Union européenne	citoyenneté européenne, libre circulation, coopération économique	Protectionnisme, armée unique, exclusion des non-européens	Monarchie, unité religieuse, langue unique (le latin)	Nationalisme, fermeture des frontières, compétition économique
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaitre et comprendre le fonctionnement de l'Union européenne	À quelles élections les citoyens étrangers européens résidant en France peuvent-ils voter ?	Les citoyens de l'Union européenne résidant en France peuvent voter et être éligibles aux élections municipales et aux élections européennes.	Uniquement aux élections présidentielles françaises	Aux élections législatives françaises et aux référendums nationaux	À toutes les élections françaises sans restriction
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Citez des exemples de libertés individuelles et collectives en France.	Liberté de circulation, liberté de mariage et de divorce, liberté d'opinion, de conscience, d'expression et de croyances.	Le droit d'avoir une armée privée	Le droit de ne pas payer d'impôts si on est en désaccord avec l'État	Le droit de ne pas se conformer aux règles communes au nom de la religion
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Quels sont les droits sociaux et économiques ?	Les droits qui visent à assurer à chaque individu des conditions de vie dignes et équitables (ex: droit au travail, droit à la protection sociale).	Le droit de choisir sa propre loi	Les droits qui concernent uniquement le droit de vote	Les droits qui garantissent l'accès à la propriété privée pour tous
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Citez les principales notions relatives aux droits fondamentaux.	Dignité humaine, intégrité physique et psychologique, citoyenneté, État de droit, démocratie, respect des droits de l'homme.	L'obéissance aveugle, la soumission au chef, l'absence de pluralité	La monarchie absolue, la théocratie, l'esclavage	La discrimination, la ségrégation, le racisme
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Quels sont les principaux textes qui garantissent les droits fondamentaux en France ?	La Constitution de la Ve République (1958), la Déclaration des droits de l'homme et du citoyen (1789), la Charte de l'environnement (2004).	Le Code de la Route, le Code Pénal, le Code du Commerce	Les Évangiles, le Coran, la Torah	Les Décrets du Roi Soleil, les Ordonnances de la IIIe République
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Par quoi les libertés individuelles sont-elles limitées ?	Les libertés sont encadrées par la loi et limitées par les libertés des autres et par la défense de l'ordre public (sécurité, tranquillité, salubrité, dignité humaine).	Par la seule volonté du Président de la République	Par les organisations religieuses	Elles ne sont limitées par rien du tout
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Citez une obligation des résidents et les conséquences du non-respect des lois.	Obligation de payer les impôts et cotisations sociales. La police et la gendarmerie assurent le respect des lois. Le non-respect entraîne des infractions (contraventions, délits, crimes).	Obligation de servir dans l'armée à vie	Obligation de suivre une seule religion	Obligation de ne pas voyager hors de France
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Quelle attitude citoyenne favorise la vie au sein de la collectivité nationale ?	Contribuer au bien collectif (par le travail), respecter les règles communes, autrui et l'environnement.	Le refus de toute intégration culturelle	L'isolement social et le refus de travailler	La soumission totale aux autorités religieuses
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Quelles sont les formes de participation des citoyens français au fonctionnement des institutions ?	Voter, être juré dans un procès.	Être juré, mais ne jamais voter	Se présenter à toutes les élections à l'âge de 15 ans	Participer aux défilés militaires obligatoirement
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Citez trois grandes périodes historiques qui ont marqué la France.	Monarchie (jusqu'en 1789), Révolution Française (dès 1789), Empire de Napoléon (création du Code Civil), Installation de la République (école laïque, gratuite et obligatoire dès 1880).	L'âge des pharaons, l'invasion des Vikings, la colonisation du Canada	L'époque des Dinosaures, l'ère glaciaire, le Moyen-Âge	La période Romaine, la Guerre de Cent Ans, la Renaissance (16e siècle)
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Citez des événements majeurs qui ont eu lieu au XXe siècle.	Grande Guerres (1914-1918 et 1939-1945), Résistance (Appel du 18 juin), Droit de vote des femmes (1944), Création de l'ONU (1945), Création de la CEE (1957).	La construction de la Tour Eiffel (1889)	La Révolution Française (1789)	L'édit de Nantes (1598)
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Quelles sont les étapes importantes de la construction de la Ve République ?	Constitution de la Ve République, Suffrage universel direct pour le président, Décolonisation (1950-1962), Abolition de la peine de mort (1981 - F. Mitterrand), Naissance de l'UE (1992) et de l'Euro (2002).	L'installation de la monarchie absolue	La création de l'école laïque et gratuite (1880)	L'instauration du droit de vote pour tous les hommes (1848)
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Citez les 4 principaux fleuves et un massif montagneux de France, ainsi que les DROM.	Fleuves (Seine, Loire, Garonne, Rhône, Rhin), Massifs montagneux (Alpes, Pyrénées, Massif Central), 5 DROM (Guadeloupe, Martinique, Guyane, La Réunion, Mayotte).	Fleuves (Nil, Amazone, Mississippi, Danube), Massif (Himalaya), DROM (Groenland)	Fleuves (Tamise, Tibre, Volga, Congo), Massif (Appalaches), DROM (Australie)	Fleuves (Seine, Loire, Garonne, Rhône), Massif (Vercors), DROM (Antarctique)
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Citez des pays voisins et des mers/océans qui bordent la France.	Frontières terrestres : Belgique, Luxembourg, Allemagne, Suisse, Italie, Monaco, Espagne, Andorre. Mers et Océans : Manche, Mer du Nord, Océan Atlantique, Mer Méditerranée.	Pays voisins : Canada, Brésil, Chine. Mers : Mer Noire	Pays voisins : Royaume-Uni, Russie, Pologne. Mers : Mer Rouge	Pays voisins : Grèce, Portugal, Irlande. Mers : Mer Baltique
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Quelle est la population française et comment est-elle répartie sur le territoire ?	Population française : environ 68 millions d'habitants. 9/10 habitent en aires urbaines. La France est la 1ère destination touristique mondiale (Grandes villes, côtes, montagnes).	Population : 10 millions. 9/10 habitent en zone rurale. La France est la dernière destination touristique mondiale.	Population : 300 millions. 9/10 habitent en zone de montagne. La France est un pays fermé au tourisme.	Population : 120 millions. La moitié habite au bord de mer. La France n'est visitée que par les Asiatiques.
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Où se situent principalement les activités économiques en France ?	Les principales activités économiques se situent à proximité des grandes villes et des axes de communication (autoroutes, voies ferrées).	Uniquement dans les zones rurales isolées	Majoritairement dans les déserts	Exclusivement le long des côtes maritimes
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Citez trois monuments historiques ou lieux emblématiques de la France.	Tour Eiffel, Arc de Triomphe, Cathédrale Notre-Dame de Paris, Château de Versailles, Mont Saint-Michel.	La Statue de la Liberté (New York), La Grande Muraille de Chine, le Colisée de Rome	Le Parthénon (Athènes), La Pyramide de Gizeh (Égypte), Le Taj Mahal (Inde)	Big Ben (Londres), Le Christ Rédempteur (Brésil), Le Kremlin (Moscou)
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Citez des artistes ou auteurs français célèbres.	Victor Hugo, Molière, Albert Camus (auteurs) ; Claude Monet, Auguste Renoir (artistes).	William Shakespeare, Léonard de Vinci, Miguel de Cervantes	Johann Wolfgang von Goethe, Fiodor Dostoïevski, Pablo Picasso	Ernest Hemingway, Jane Austen, Akira Kurosawa
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Citez des plats typiques de la gastronomie française.	Bœuf Bourguignon, Coq au Vin, Ratatouille, Crêpes, Macarons, Baguette, Fromages.	Sushi, Tacos, Pizza, Kebab, Curry Indien	Hamburger, Hot-dog, Fish and Chips	Paella, Couscous, Fondue Suisse
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Quelles sont les principales fêtes célébrées en France ?	Fête Nationale (14 juillet - bal des pompiers, défilé militaire), Noël (repas de famille), Nouvel An, Fête du Travail (1er mai).	Jour de l'Indépendance Américaine (4 juillet), Thanksgiving	Halloween (fête religieuse), Mardi Gras (fête nationale)	La Fête de la Bière (Oktoberfest), La Saint-Patrick
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Quel est le rayonnement de la langue française dans le monde ?	5e langue mondiale, parlée par 321 millions de personnes, promue par l'Organisation Internationale de la Francophonie (OIF).	1ère langue mondiale, parlée par 5 milliards de personnes, sans promotion internationale	100e langue mondiale, parlée uniquement par les Français de naissance	Langue en voie de disparition, parlée seulement en France et au Québec
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Citez des démarches administratives du quotidien.	Assurance responsabilité civile, échange du permis de conduire, déclaration des revenus, changement d'adresse.	Achat d'armes, constitution d'une milice privée, organisation de manifestations illégales	Voyages à l'étranger sans passeport, refus de payer les taxes locales	Prise de rendez-vous à la mairie pour rencontrer le Président de la République
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Où effectue-t-on les démarches de demande et renouvellement du titre de séjour ?	Procédures de demande et renouvellement du titre de séjour (à la préfecture/sous-préfecture).	À la mairie de son lieu de naissance	Au consulat de son pays d'origine	Au Palais de l'Élysée
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Quels sont les principes et procédures d'accès à la nationalité française ?	Principe d'assimilation. Procédures par déclaration (mariage, ascendants) ou par demande de naturalisation (résidence).	Le principe de l'hérédité (seuls les enfants de Français l'obtiennent)	La procédure par tirage au sort parmi les résidents étrangers	L'achat de la nationalité contre une forte somme d'argent
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Où doit-on déclarer une naissance, un mariage, ou un décès ?	Déclaration d'état civil (naissance, mariage, décès) à la mairie. Démarches auprès des organismes sociaux (CAF, CPAM) pour les prestations familiales et sociales.	Au commissariat de police le plus proche	Auprès de son ambassade d'origine	Auprès de l'église ou de la mosquée locale
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Que doit-on connaître concernant le logement en France ?	Connaître les droits et obligations du propriétaire et du locataire (bail, dépôt de garantie, préavis).	Les règles de construction d'un nouveau bâtiment uniquement	La liste de tous les propriétaires en France	Comment ne pas payer son loyer
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Citez les différentes offres de soins disponibles.	Hôpitaux, cliniques, urgences, médecin traitant, spécialistes.	Les soins sont uniquement disponibles à domicile	Seuls les médecins généralistes sont disponibles	Les offres de soins sont gérées uniquement par les organisations religieuses
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Comment la prise en charge des soins de santé est-elle assurée ?	Assurance maladie (Sécurité Sociale) et Mutuelle (complémentaire santé).	Uniquement par les donations privées	Uniquement par les économies personnelles des citoyens	Uniquement par une taxe sur les produits de luxe
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Y a-t-il des obligations vaccinales en France ?	Certains vaccins sont obligatoires pour les enfants (ex: diphtérie, tétanos, polio).	Tous les vaccins sont interdits	La vaccination est obligatoire à l'âge adulte uniquement	Seuls les vaccins contre la grippe sont obligatoires
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Quels sont les numéros d'urgence à connaître ?	15 (SAMU), 17 (Police/Gendarmerie), 18 (Pompiers), 112 (Numéro d'urgence européen).	0800 (numéro vert), 3639 (Météo France), 121 (Renseignements)	911 (États-Unis), 999 (Royaume-Uni), 110 (Japon)	Les numéros d'urgence sont différents dans chaque région
Vivre dans la société française	L'accès aux soins	Connaître les droits du patient	Quel est le principe concernant le choix du praticien ?	Le patient est libre de choisir son médecin traitant et son établissement de soin.	Le choix du praticien est imposé par l'Assurance maladie	Seul un médecin d'origine française peut être choisi	Le patient doit consulter le médecin le plus proche de son domicile
Vivre dans la société française	L'accès aux soins	Connaître les droits du patient	Quel est le principe de confidentialité dans le domaine de la santé ?	Respect du secret médical : le professionnel de santé ne peut divulguer les informations concernant le patient.	Le médecin doit divulguer les informations au voisinage	Le médecin doit informer l'employeur du patient	Le secret médical ne s'applique qu'aux crimes
Vivre dans la société française	L'accès aux soins	Connaître les droits du patient	Quel droit fondamental le patient possède-t-il concernant son état de santé ?	Le patient a le droit d'être informé sur son état de santé et sur les traitements proposés.	Le patient n'a pas le droit de connaître son diagnostic	Le patient doit accepter tous les traitements proposés par le médecin	Le patient peut choisir son traitement même s'il est dangereux pour la santé publique
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Quel est le cadre général du travail en France (durée, congés, droits) ?	Durée légale de travail (35h/semaine), congés payés, contrat de travail, droit syndical, sécurité au travail.	Durée légale de 60h/semaine, pas de congés payés, interdiction de tout syndicat	Durée légale de 50h/semaine, les jours de maladie ne sont pas payés	Les travailleurs n'ont aucun droit de se plaindre de leurs conditions
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Citez des acteurs ou organismes pour la recherche d'emploi.	Pôle Emploi, agences d'intérim, sites d'emploi, réseaux professionnels.	Le SAMU, les Pompiers, la Gendarmerie	Le Conseil Constitutionnel, le Sénat, l'Assemblée Nationale	La Banque de France, l'URSSAF, la CAF
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Citez des acteurs ou organismes pour entreprendre en France.	Chambres de Commerce et d'Industrie (CCI), Chambres de Métiers et de l'Artisanat (CMA), URSSAF, Guichet unique (Inpi).	Le Défenseur des Droits, le Conseil d'État	Les hôpitaux, les écoles, les musées	Le Ministère de la Défense, l'Armée de Terre
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre la notion d'autorité parentale	Quelles sont les obligations et responsabilités des parents envers leurs enfants mineurs ?	Autorité parentale (droit et devoir de garde, surveillance, éducation et protection de l'enfant).	L'obligation pour les enfants de travailler pour subvenir aux besoins des parents	L'interdiction de donner une éducation à ses enfants	Le droit de ne s'occuper que de la nourriture des enfants
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre la notion d'autorité parentale	Quel est le cadre légal de protection des enfants ?	Protection contre la maltraitance et le droit au respect de leur intégrité physique et morale (ex: interdiction des châtiments corporels).	La protection est assurée uniquement par les associations religieuses	Les parents ont le droit de frapper leurs enfants pour les éduquer	Les enfants n'ont pas le droit au respect de leur intégrité morale
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre le système éducatif	Quel est le principe de l'obligation de scolarité en France ?	Instruction obligatoire (de 3 à 16 ans). Obligation de scolarité et interdiction de contester les enseignements (principe de neutralité).	L'école est obligatoire jusqu'à 25 ans	Les parents peuvent choisir les matières que leurs enfants suivent (ex: pas de sciences)	L'école privée est le seul mode de scolarisation légal
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre le système éducatif	Comment le système scolaire est-il organisé ?	École maternelle, École primaire, Collège, Lycée, Enseignement supérieur.	Organisation en trois niveaux : l'École du village, le Lycée militaire, l'Université de la capitale	École religieuse, École professionnelle, École à l'étranger	Un seul niveau de scolarité de 3 à 18 ans
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre le système éducatif	Quelles sont les obligations des parents d'élèves ?	Obligation d'instruction (scolariser l'enfant ou assurer l'instruction en famille) et de respecter le règlement intérieur de l'école.	Les parents doivent enseigner la religion à l'école	Les parents peuvent contester tous les enseignements qui ne correspondent pas à leurs croyances	Les parents doivent payer les professeurs de l'école publique`;

  questions: Array<{ question: string; answer: string; thematique?: string; notions?: string; distractors?: string[] }> = [];
  @Input() maxQuestions?: number | null;
  pool: string[] = [];
  current = 0;
  correctCount = 0;
  incorrectCount = 0;
  choices: string[] = [];
  selected: string | null = null;
  finished = false;

  ngOnInit(): void {
    this.questions = this.parseTsv(this.rawTsv);
    this.pool = this.buildOptionsPool(this.questions);
    this.shuffle(this.questions);
    // If maxQuestions specified, select that many random questions
    if (this.maxQuestions && this.maxQuestions > 0 && this.questions.length > this.maxQuestions) {
      this.questions = this.questions.slice(0, this.maxQuestions);
      this.shuffle(this.questions);
    }
    if (this.questions.length) this.renderQuestion();
  }

  private parseTsv(tsv: string) {
    const lines = (tsv || '').split(/\r?\n/).map(l => l.trim()).filter(l => l.length > 0);
    if (lines.length <= 1) return [];
    const header = lines[0].split('\t').map(h => h.trim());
    const qIndex = header.findIndex(h => /question/i.test(h));
    const aIndex = header.findIndex(h => /reponse|réponse|answer/i.test(h));
    const themIndex = header.findIndex(h => /th[eé]matique|thematique/i.test(h));
    const notionsIndex = header.findIndex(h => /notion/i.test(h));
    // find distractor columns (accept English and French variants, or any header containing 'distract' or 'option')
    const distractorIndexes = header
      .map((h, idx) => ({ h, idx }))
      .filter(x => /distract|option/i.test(x.h))
      .map(x => x.idx);

    const items: Array<{question:string, answer:string, thematique?: string, notions?: string, distractors?: string[]}> = [];
    for (let i = 1; i < lines.length; i++) {
      const cols = lines[i].split('\t');
      const q = (cols[qIndex] || cols[3] || '').trim();
      const a = (cols[aIndex] || cols[4] || '').trim();
      const t = (cols[themIndex] || cols[0] || '').trim();
      const n = (cols[notionsIndex] || cols[1] || '').trim();
      const distractors = distractorIndexes.map(ix => (cols[ix] || '').trim()).filter(Boolean);
      if (q && a) items.push({ question: q, answer: a, thematique: t, notions: n, distractors: distractors.length ? distractors : undefined });
    }
    return items;
  }

  private buildOptionsPool(questions: Array<{question:string,answer:string}>) {
    return questions.map(q => q.answer).filter(Boolean);
  }

  private shuffle<T>(arr: T[]) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
  }

  private makeChoicesFor(index: number) {
    const q = this.questions[index];
    const correct = q.answer;
    // Use only the distractors provided for this question (do not mix answers from other questions).
    // If the TSV provides fewer than 3 distractors, we'll show only the provided ones plus the correct answer.
    const distractors: string[] = (q.distractors || []).map(d => d.trim()).filter(d => d && d !== correct);
    const opts = [correct, ...distractors];
    this.shuffle(opts);
    return opts;
  }

  renderQuestion() {
    if (!this.questions.length) return;
    this.choices = this.makeChoicesFor(this.current);
    this.selected = null;
    this.finished = false;
  }

  // progress percentage for the question accent bar (0-100)
  get progressPercent(): number {
    const total = this.questions.length || 1;
    if (this.finished) return 100;
    if (total <= 1) return 100;
    // use current index as progress; shows 0% at first question and 100% at last
    const pct = Math.round((this.current / (total - 1)) * 100);
    return Math.max(0, Math.min(100, pct));
  }

  selectOption(option: string) {
    if (this.selected) return; // already selected
    this.selected = option;
    const correct = this.questions[this.current].answer;
    if (option === correct) {
      this.correctCount++;
    } else {
      this.incorrectCount++;
    }
  }

  next() {
    if (this.current >= this.questions.length - 1) {
      this.finished = true;
      return;
    }
    this.current++;
    this.renderQuestion();
  }

  restart() {
    this.correctCount = 0;
    this.incorrectCount = 0;
    this.current = 0;
    this.shuffle(this.questions);
    this.renderQuestion();
  }
}