import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-multi-choice-test',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './multi-choice-test.component.html',
  styleUrls: ['./multi-choice-test.component.css']
})
export class MultiChoiceTestComponent implements OnInit {
  // Embedded TSV (header + a few sample rows). Replace or extend with the full dataset if desired.
    // Embedded TSV (header + a few sample rows). You can add three optional distractor columns
    // named Distractor1, Distractor2, Distractor3 (or any header containing 'distractor').
    // Replace or extend with the full dataset if desired.
  private rawTsv = `Thématique	Notions	Connaisance	Question	Reponse	Distracteur 1	Distracteur 2	Distracteur 3
Principes et valeurs de la République	Devise et symboles de la République	Connaitre et comprendre la République	Qu'est-ce que c'est une republique?	Un mode d'organisation des pouvoirs	Une forme de monarchie parlementaire	Une communauté fondée sur une ethnie unique	Un système où un seul homme détient tous les pouvoirs
Principes et valeurs de la République	Devise et symboles de la République	Connaitre et comprendre la République	Que dit l'art. 1er de la Constitution de l'unité et indivisibilité de la République?	« La France est une République indivisible, laïque, démocratique et sociale »	« La France est une monarchie constitutionnelle, tolérante, sociale et unie »	« La France est une nation unie, respectueuse des traditions et de l'histoire »	« La France est une démocratie libérale, unie et décentralisée »
Principes et valeurs de la République	Devise et symboles de la République	Connaitre et comprendre la République	Que dit l'art. 3 de la Constitution de la souveraineté nationale?	« La souveraineté nationale appartient au peuple qui l'exerce par ses représentants et par la voie du référendum »	« La souveraineté nationale appartient au chef de l'État qui l'exerce par décret »	« La souveraineté est déléguée aux représentants élus pour une durée illimitée »	« La souveraineté est partagée entre le Parlement, le gouvernement et le peuple »
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : liberté	Quel est le sens de la liberté?	Respecter l'intégrité et la diversité des croyances et des convictions d'autrui.	Faire tout ce que l'on veut tant que ça ne nuit pas à autrui	L'absence totale de contrainte et de loi	La possibilité de choisir son gouvernement et ses représentants
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : liberté	Quelles sont les différents types de libertés individuelles et collectives?	Pensée, opinion, expression, religion, travail, circulation, réunion, association, mariage (polygamie interdite).	Liberté d'entreprendre, de manifester, de vote et d'accès à la propriété	Liberté de culte, de circulation, de défense nationale et d'instruction publique	Liberté de la presse, de la chasse, d'importation et d'exportation
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : liberté	Quelles sont les différentes formes d'engagement dans la vie associative et locale?	Droit de créer et d'adhérer à une association, droit syndical.	L'obligation de faire le service militaire	Le droit de se présenter à toutes les élections à partir de 16 ans	Le droit de manifester avec des armes
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Quel est le sens de l'égalité?	Égalité des droits et des devoirs, entre les femmes et les hommes, et devant la loi.	Le fait que tout le monde ait exactement les mêmes biens et revenus	Le fait de permettre aux citoyens de choisir leur niveau d'imposition	Le fait que seules les personnes nées en France aient les mêmes droits
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Que signifie respecter les droits d'autrui et accepter les différences?	Lutte contre les discriminations, le racisme, l'antisémitisme et la haine anti-LGBT.	Le fait de favoriser uniquement sa communauté d'origine	L'interdiction de toute critique envers les autorités	La promotion d'une seule ethnie et culture nationale
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Quel est le sens de la fraternité ?	Voir en autrui un semblable malgré les différences : une fraternité civique, non ethnique ou religieuse.	Le fait de favoriser uniquement ses proches et sa famille	La liberté totale de ne pas aider les personnes en difficulté	L'obligation de partager la même religion avec ses voisins
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Differentes formes de solidarité?	Collective (les impôts financent les services publics, défense de la Nation) et intergénérationnelle (ex : retraites).	Uniquement l'aide entre membres d'une même communauté religieuse	L'obligation pour les jeunes de financer à 100% les retraites	Le droit de s'isoler et de refuser toute contribution collective
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Quel est le drapeau de la France?	Bleu, Blanc, Rouge (Le drapeau tricolore).	Vert, blanc, rouge	Bleu, jaune, rouge	Bleu, blanc, jaune
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Comment s'appele l'hymne?	La Marseillaise	Le Chant des Partisans	Le Temps des Cerises	L'Internationale
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Quelle est la devise de la France?	Liberté, Égalité, Fraternité	Honneur et Patrie	Travail, Famille, Patrie	Pour la France
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Qui est la Marianne?	Symbole de la République représentant la Liberté et la Raison.	La femme du Président de la République	Une ancienne Reine de France	La sainte patronne de Paris
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Quuand est la fête nationale ?	14 juillet (prise de la Bastille)	Le 11 novembre	Le 8 mai	Le 1er mai
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Pourquoi le coq est le symbole de la France ?	Jeu de mots : le latin gallus signifie à la fois « gaulois » et « coq ».	Parce qu'il est un animal craintif et humble	C'est un emblème choisi par Napoléon Ier	Il est le seul animal capable de voler très haut
Principes et valeurs de la République	Devise et symboles de la République	Savoir que le français est la langue nationale et officielle	Quel est la langue officielle de la republique?	« Le français est la langue de la République française » (article 2 de la Constitution).	Le latin	L'anglais et le français sont officiels	La langue régionale majoritaire
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Comment la France est devenue laïque?	Loi de 1905, aboutissement de siècles de lutte entre pouvoirs religieux et politiques ; elle organise les relations entre l'État et les religions.	Par un décret du Roi Louis XIV au 17e siècle	Uniquement par une décision de Napoléon III	Grâce à une consultation populaire en 1999
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quel est le principe de liberté de conscience?	Liberté de croire, de ne pas croire ou de changer de religion (droit à l'apostasie), et droit au blasphème, dans le respect de l'ordre public.	L'obligation pour l'État de financer toutes les croyances	Le droit de ne respecter aucune loi au nom de sa religion	Le fait que seul l'athéisme est autorisé
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quelle est la place des religions en France et le rôle de l'Etat face a elles?	Séparation des Églises et de l'État, libre organisation des cultes ; l'État protège les lieux de culte et reste neutre.	L'État doit construire de nouveaux lieux de culte pour toutes les religions	L'État intervient directement dans l'organisation interne des cultes	L'État interdit toute pratique religieuse en public
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Que dit le principe de laïcité pour l'usager du service public?	Égalité de tous devant le service public ; expression religieuse possible dans le respect de l'ordre public, sans prosélytisme.	Les usagers du service public doivent être neutres et ne rien exprimer de leurs convictions	Ils peuvent exiger un traitement différent en fonction de leur religion	Ils doivent cacher tout signe d'appartenance religieuse dans l'espace public
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quel est le principe de laïcité au travail?	Neutralité obligatoire pour les agents publics ; dans le privé, restrictions possibles pour sécurité, hygiène ou bon fonctionnement de l'entreprise.	Les agents publics peuvent faire du prosélytisme sur leur lieu de travail	La religion est interdite dans toutes les entreprises privées	L'employeur est obligé de modifier les horaires de travail pour toutes les pratiques religieuses
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quel est le principe de laïcité à l'école publique?	Elle protège la liberté de choix de chaque enfant : impossible de choisir ses enseignements selon ses croyances.	Les parents peuvent demander la suppression de certains cours (sciences, histoire) au nom de la religion	L'école publique est obligatoire pour tous les enfants, y compris les enfants d'immigrés	Les professeurs sont obligés d'enseigner la religion majoritaire
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Quel est le principe d'Etat de droit?	La loi s'applique à tous, y compris aux autorités publiques, ce qui garantit les droits et libertés de chacun.	Le gouvernement peut décider seul ce qui est loi	Le Président de la République est au-dessus de toutes les lois	Les lois sont faites uniquement par les juges
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Quels sont les trois pouvoirs?	législatif, exécutif, autorité judiciaire	Religieux, Militaire, Économique	Local, Régional, National	Éducatif, Sanitaire, Social
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Decrit le rôle des trois pouvoirs et les principaux acteurs	faire les lois (députés et sénateurs), appliquer les lois (gouvernement), rendre la justice (les juges) ;	faire les lois (le Président), appliquer les lois (les Préfets), rendre la justice (la Police)	faire les lois (les Maires), appliquer les lois (les Citoyens), rendre la justice (le Parlement)	faire les lois (le Conseil Constitutionnel), appliquer les lois (l'ONU), rendre la justice (la Cour d'Appel)
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Decrit le principe de la séparation des pouvoirs et sa mise en œuvre	Article 16 de la DDHC : équilibre entre un gouvernement responsable devant le Parlement, un président élu au suffrage direct et une justice indépendante.	Le Président de la République cumule les trois pouvoirs pour plus d'efficacité	Le Parlement peut juger directement les citoyens et les condamner	Le pouvoir judiciaire est sous l'autorité du Premier ministre
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre le droit de vote et les élections	Quelles sont les conditions pour voter en France?	Nationalité française, majorité, et ne pas avoir été privé de ses droits civils et politiques.	Être propriétaire d'un bien immobilier, avoir 25 ans et être né en France	Ne pas avoir de casier judiciaire, avoir 21 ans et résider en France depuis 10 ans	Être salarié d'une entreprise française et avoir une carte d'identité
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre le droit de vote et les élections	Que dit le principe de pluralité des partis?	Condition nécessaire de la démocratie, assurant la représentation des différents courants socioculturels.	Le gouvernement doit toujours être composé d'un seul parti politique	Seuls deux partis politiques majeurs sont autorisés	Les partis politiques doivent être financés uniquement par l'État
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le découpage administratif et institutionnel	Citez les trois niveaux de l'organisation territoriale de l'État.	Trois niveaux : Commune, Département, Région ; l'État y est représenté par les préfectures.	Les trois niveaux sont : le Canton, l'Arrondissement, la Circonscription	Les trois niveaux sont : l'Europe, l'État, la Commune	Les trois niveaux sont : l'Armée, la Police, les Impôts
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le découpage administratif et institutionnel	Quelles sont les principales institutions politiques de la Ve République?	Exécutif (président, gouvernement), législatif (Assemblée nationale, Sénat), judiciaire (tribunaux) ; ainsi que le Conseil constitutionnel, le Défenseur des droits, la Banque de France.	Le Roi, la Couronne, les Ducs et les Seigneurs	Le Saint-Siège, l'Évêché, le Clergé	Le FMI, la Banque Mondiale, l'OTAN
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le fonctionnement démocratique	Decrit le rôle des acteurs politiques au niveau national et local	le président de la République, le Premier ministre, le maire ;	Le rôle des acteurs politiques est de juger les citoyens	Leur rôle est de diriger l'armée et de faire la guerre	Leur rôle est de nommer les fonctionnaires et d'attribuer les honneurs
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le fonctionnement démocratique	Quelles sont les différents types d'élections?	présidentielles, législatives, européennes, locales	Élection du Préfet, du Juge, du Général de l'armée	Élection du Pape, du Chef de la police, et du PDG de la SNCF	Élection des chefs d'entreprise et des directeurs d'école
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le fonctionnement démocratique	Quelle est la durée des principaux mandats électifs (Président, Députés, Maires) ?	Président et Députés : 5 ans ; Maires et Sénateurs : 6 ans.	Président de la République : 7 ans ; Députés : 4 ans ; Maires : 3 ans	Tous les mandats sont de 4 ans renouvelables une fois	La durée des mandats est à vie ou jusqu'à la retraite
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaître et comprendre les fondements de l'Union européenne	Quelles sont les principales étapes historiques et le nombre actuel d'États membres de l'UE ?	L'UE a été fondée sur le Traité de Rome (1957) et compte actuellement 27 États membres.	L'UE a été fondée en 1989 après la chute du Mur de Berlin et compte 15 membres	L'UE a été fondée en 1945 après la Seconde Guerre mondiale et compte 50 membres	L'UE a été fondée sur l'Accord de Schengen (1995) et compte 10 membres
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaître et comprendre les fondements de l'Union européenne	Quels sont le drapeau et l'hymne de l'Union européenne?	Hymne : l'Ode à la joie (Beethoven) ; drapeau bleu avec un cercle de 12 étoiles dorées.	Hymne: La Marseillaise, drapeau vert avec 27 étoiles	Hymne: God Save the Queen, drapeau rouge avec une croix	Hymne: L'Internationale, drapeau blanc avec un blason
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaitre et comprendre le fonctionnement de l'Union européenne	Quelles sont les institutions européennes ?	Parlement européen, Conseil de l'Union européenne, Commission européenne	Le FMI, l'OTAN, l'ONU	La Banque Mondiale, la CPI, la CJUE	Le Conseil de l'Europe, le Conseil Constitutionnel, la Cour de Cassation
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaitre et comprendre le fonctionnement de l'Union européenne	Quels sont les principes essentiels de l'Union européenne	citoyenneté européenne, libre circulation, coopération économique	Protectionnisme, armée unique, exclusion des non-européens	Monarchie, unité religieuse, langue unique (le latin)	Nationalisme, fermeture des frontières, compétition économique
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaitre et comprendre le fonctionnement de l'Union européenne	À quelles élections les citoyens étrangers européens résidant en France peuvent-ils voter ?	Élections municipales et élections européennes.	Uniquement aux élections présidentielles françaises	Aux élections législatives françaises et aux référendums nationaux	À toutes les élections françaises sans restriction
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Citez des exemples de libertés individuelles et collectives en France.	Circulation, mariage et divorce, opinion, conscience, expression, croyances.	Le droit d'avoir une armée privée	Le droit de ne pas payer d'impôts si on est en désaccord avec l'État	Le droit de ne pas se conformer aux règles communes au nom de la religion
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Quels sont les droits sociaux et économiques ?	Droits assurant des conditions de vie dignes (ex : travail, protection sociale).	Le droit de choisir sa propre loi	Les droits qui concernent uniquement le droit de vote	Les droits qui garantissent l'accès à la propriété privée pour tous
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Citez les principales notions relatives aux droits fondamentaux.	Dignité humaine, intégrité physique et psychologique, citoyenneté, État de droit, démocratie.	L'obéissance aveugle, la soumission au chef, l'absence de pluralité	La monarchie absolue, la théocratie, l'esclavage	La discrimination, la ségrégation, le racisme
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Quels sont les principaux textes qui garantissent les droits fondamentaux en France ?	La Constitution de la Ve République (1958), la Déclaration des droits de l'homme et du citoyen (1789), la Charte de l'environnement (2004).	Le Code de la Route, le Code Pénal, le Code du Commerce	Les Évangiles, le Coran, la Torah	Les Décrets du Roi Soleil, les Ordonnances de la IIIe République
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Par quoi les libertés individuelles sont-elles limitées ?	Par la loi, les libertés d'autrui et l'ordre public (sécurité, tranquillité, salubrité, dignité humaine).	Par la seule volonté du Président de la République	Par les organisations religieuses	Elles ne sont limitées par rien du tout
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Citez une obligation des résidents et les conséquences du non-respect des lois.	Payer impôts et cotisations sociales ; le non-respect des lois entraîne des infractions (contraventions, délits, crimes).	Obligation de servir dans l'armée à vie	Obligation de suivre une seule religion	Obligation de ne pas voyager hors de France
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Quelle attitude citoyenne favorise la vie au sein de la collectivité nationale ?	Contribuer au bien collectif (par le travail), respecter les règles communes, autrui et l'environnement.	Le refus de toute intégration culturelle	L'isolement social et le refus de travailler	La soumission totale aux autorités religieuses
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Quelles sont les formes de participation des citoyens français au fonctionnement des institutions ?	Voter, être juré dans un procès.	Être juré, mais ne jamais voter	Se présenter à toutes les élections à l'âge de 15 ans	Participer aux défilés militaires obligatoirement
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Citez trois grandes périodes historiques qui ont marqué la France.	Monarchie (avant 1789), Révolution française (1789), Empire napoléonien (Code Civil), République (école laïque dès 1880).	L'âge des pharaons, l'invasion des Vikings, la colonisation du Canada	L'époque des Dinosaures, l'ère glaciaire, le Moyen-Âge	La période Romaine, la Guerre de Cent Ans, la Renaissance (16e siècle)
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Citez des événements majeurs qui ont eu lieu au XXe siècle.	Guerres mondiales (1914-1918, 1939-1945), Appel du 18 juin, droit de vote des femmes (1944), création de l'ONU (1945) et de la CEE (1957).	La construction de la Tour Eiffel (1889)	La Révolution Française (1789)	L'édit de Nantes (1598)
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Quelles sont les étapes importantes de la construction de la Ve République ?	Constitution de la Ve République, suffrage universel direct, décolonisation (1950-1962), abolition de la peine de mort (1981), naissance de l'UE (1992) et de l'Euro (2002).	L'installation de la monarchie absolue	La création de l'école laïque et gratuite (1880)	L'instauration du droit de vote pour tous les hommes (1848)
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Citez les 4 principaux fleuves et un massif montagneux de France, ainsi que les DROM.	Fleuves (Seine, Loire, Garonne, Rhône, Rhin), Massifs montagneux (Alpes, Pyrénées, Massif Central), 5 DROM (Guadeloupe, Martinique, Guyane, La Réunion, Mayotte).	Fleuves (Nil, Amazone, Mississippi, Danube), Massif (Himalaya), DROM (Groenland)	Fleuves (Tamise, Tibre, Volga, Congo), Massif (Appalaches), DROM (Australie)	Fleuves (Seine, Loire, Garonne, Rhône), Massif (Vercors), DROM (Antarctique)
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Citez des pays voisins et des mers/océans qui bordent la France.	Frontières terrestres : Belgique, Luxembourg, Allemagne, Suisse, Italie, Monaco, Espagne, Andorre. Mers et Océans : Manche, Mer du Nord, Océan Atlantique, Mer Méditerranée.	Pays voisins : Canada, Brésil, Chine. Mers : Mer Noire	Pays voisins : Royaume-Uni, Russie, Pologne. Mers : Mer Rouge	Pays voisins : Grèce, Portugal, Irlande. Mers : Mer Baltique
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Quelle est la population française et comment est-elle répartie sur le territoire ?	Environ 68 millions d'habitants, 9/10 en zone urbaine ; 1ère destination touristique mondiale.	Population : 10 millions. 9/10 habitent en zone rurale. La France est la dernière destination touristique mondiale.	Population : 300 millions. 9/10 habitent en zone de montagne. La France est un pays fermé au tourisme.	Population : 120 millions. La moitié habite au bord de mer. La France n'est visitée que par les Asiatiques.
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Où se situent principalement les activités économiques en France ?	Près des grandes villes et des axes de communication (autoroutes, voies ferrées).	Uniquement dans les zones rurales isolées	Majoritairement dans les déserts	Exclusivement le long des côtes maritimes
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Citez trois monuments historiques ou lieux emblématiques de la France.	Tour Eiffel, Arc de Triomphe, Cathédrale Notre-Dame de Paris, Château de Versailles, Mont Saint-Michel.	La Statue de la Liberté (New York), La Grande Muraille de Chine, le Colisée de Rome	Le Parthénon (Athènes), La Pyramide de Gizeh (Égypte), Le Taj Mahal (Inde)	Big Ben (Londres), Le Christ Rédempteur (Brésil), Le Kremlin (Moscou)
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Citez des artistes ou auteurs français célèbres.	Victor Hugo, Molière, Albert Camus (auteurs) ; Claude Monet, Auguste Renoir (artistes).	William Shakespeare, Léonard de Vinci, Miguel de Cervantes	Johann Wolfgang von Goethe, Fiodor Dostoïevski, Pablo Picasso	Ernest Hemingway, Jane Austen, Akira Kurosawa
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Citez des plats typiques de la gastronomie française.	Bœuf Bourguignon, Coq au Vin, Ratatouille, Crêpes, Macarons, Baguette, Fromages.	Sushi, Tacos, Pizza, Kebab, Curry Indien	Hamburger, Hot-dog, Fish and Chips	Paella, Couscous, Fondue Suisse
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Quelles sont les principales fêtes célébrées en France ?	Fête Nationale (14 juillet), Noël, Nouvel An, Fête du Travail (1er mai).	Jour de l'Indépendance Américaine (4 juillet), Thanksgiving	Halloween (fête religieuse), Mardi Gras (fête nationale)	La Fête de la Bière (Oktoberfest), La Saint-Patrick
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Quel est le rayonnement de la langue française dans le monde ?	5e langue mondiale, 321 millions de locuteurs, promue par l'OIF.	1ère langue mondiale, parlée par 5 milliards de personnes, sans promotion internationale	100e langue mondiale, parlée uniquement par les Français de naissance	Langue en voie de disparition, parlée seulement en France et au Québec
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Citez des démarches administratives du quotidien.	Assurance responsabilité civile, échange du permis de conduire, déclaration des revenus, changement d'adresse.	Achat d'armes, constitution d'une milice privée, organisation de manifestations illégales	Voyages à l'étranger sans passeport, refus de payer les taxes locales	Prise de rendez-vous à la mairie pour rencontrer le Président de la République
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Où effectue-t-on les démarches de demande et renouvellement du titre de séjour ?	À la préfecture ou sous-préfecture.	À la mairie de son lieu de naissance	Au consulat de son pays d'origine	Au Palais de l'Élysée
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Quels sont les principes et procédures d'accès à la nationalité française ?	Par déclaration (mariage, ascendants) ou par naturalisation (résidence), selon le principe d'assimilation.	Le principe de l'hérédité (seuls les enfants de Français l'obtiennent)	La procédure par tirage au sort parmi les résidents étrangers	L'achat de la nationalité contre une forte somme d'argent
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Où doit-on déclarer une naissance, un mariage, ou un décès ?	À la mairie (état civil) ; démarches sociales auprès de la CAF et de la CPAM.	Au commissariat de police le plus proche	Auprès de son ambassade d'origine	Auprès de l'église ou de la mosquée locale
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Que doit-on connaître concernant le logement en France ?	Connaître les droits et obligations du propriétaire et du locataire (bail, dépôt de garantie, préavis).	Les règles de construction d'un nouveau bâtiment uniquement	La liste de tous les propriétaires en France	Comment ne pas payer son loyer
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Citez les différentes offres de soins disponibles.	Hôpitaux, cliniques, urgences, médecin traitant, spécialistes.	Les soins sont uniquement disponibles à domicile	Seuls les médecins généralistes sont disponibles	Les offres de soins sont gérées uniquement par les organisations religieuses
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Comment la prise en charge des soins de santé est-elle assurée ?	Assurance maladie (Sécurité Sociale) et Mutuelle (complémentaire santé).	Uniquement par les donations privées	Uniquement par les économies personnelles des citoyens	Uniquement par une taxe sur les produits de luxe
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Y a-t-il des obligations vaccinales en France ?	Certains vaccins sont obligatoires pour les enfants (ex: diphtérie, tétanos, polio).	Tous les vaccins sont interdits	La vaccination est obligatoire à l'âge adulte uniquement	Seuls les vaccins contre la grippe sont obligatoires
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Quels sont les numéros d'urgence à connaître ?	15 (SAMU), 17 (Police/Gendarmerie), 18 (Pompiers), 112 (Numéro d'urgence européen).	0800 (numéro vert), 3639 (Météo France), 121 (Renseignements)	911 (États-Unis), 999 (Royaume-Uni), 110 (Japon)	Les numéros d'urgence sont différents dans chaque région
Vivre dans la société française	L'accès aux soins	Connaître les droits du patient	Quel est le principe concernant le choix du praticien ?	Libre choix du médecin traitant et de l'établissement de soin.	Le choix du praticien est imposé par l'Assurance maladie	Seul un médecin d'origine française peut être choisi	Le patient doit consulter le médecin le plus proche de son domicile
Vivre dans la société française	L'accès aux soins	Connaître les droits du patient	Quel est le principe de confidentialité dans le domaine de la santé ?	Secret médical : interdiction de divulguer les informations concernant le patient.	Le médecin doit divulguer les informations au voisinage	Le médecin doit informer l'employeur du patient	Le secret médical ne s'applique qu'aux crimes
Vivre dans la société française	L'accès aux soins	Connaître les droits du patient	Quel droit fondamental le patient possède-t-il concernant son état de santé ?	Droit d'être informé sur son état de santé et sur les traitements proposés.	Le patient n'a pas le droit de connaître son diagnostic	Le patient doit accepter tous les traitements proposés par le médecin	Le patient peut choisir son traitement même s'il est dangereux pour la santé publique
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Quel est le cadre général du travail en France (durée, congés, droits) ?	Durée légale de travail (35h/semaine), congés payés, contrat de travail, droit syndical, sécurité au travail.	Durée légale de 60h/semaine, pas de congés payés, interdiction de tout syndicat	Durée légale de 50h/semaine, les jours de maladie ne sont pas payés	Les travailleurs n'ont aucun droit de se plaindre de leurs conditions
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Citez des acteurs ou organismes pour la recherche d'emploi.	Pôle Emploi, agences d'intérim, sites d'emploi, réseaux professionnels.	Le SAMU, les Pompiers, la Gendarmerie	Le Conseil Constitutionnel, le Sénat, l'Assemblée Nationale	La Banque de France, l'URSSAF, la CAF
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Citez des acteurs ou organismes pour entreprendre en France.	Chambres de Commerce et d'Industrie (CCI), Chambres de Métiers et de l'Artisanat (CMA), URSSAF, Guichet unique (Inpi).	Le Défenseur des Droits, le Conseil d'État	Les hôpitaux, les écoles, les musées	Le Ministère de la Défense, l'Armée de Terre
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre la notion d'autorité parentale	Quelles sont les obligations et responsabilités des parents envers leurs enfants mineurs ?	Autorité parentale (droit et devoir de garde, surveillance, éducation et protection de l'enfant).	L'obligation pour les enfants de travailler pour subvenir aux besoins des parents	L'interdiction de donner une éducation à ses enfants	Le droit de ne s'occuper que de la nourriture des enfants
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre la notion d'autorité parentale	Quel est le cadre légal de protection des enfants ?	Protection contre la maltraitance ; interdiction des châtiments corporels.	La protection est assurée uniquement par les associations religieuses	Les parents ont le droit de frapper leurs enfants pour les éduquer	Les enfants n'ont pas le droit au respect de leur intégrité morale
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre le système éducatif	Quel est le principe de l'obligation de scolarité en France ?	Instruction obligatoire de 3 à 16 ans ; interdiction de contester les enseignements (principe de neutralité).	L'école est obligatoire jusqu'à 25 ans	Les parents peuvent choisir les matières que leurs enfants suivent (ex: pas de sciences)	L'école privée est le seul mode de scolarisation légal
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre le système éducatif	Comment le système scolaire est-il organisé ?	École maternelle, École primaire, Collège, Lycée, Enseignement supérieur.	Organisation en trois niveaux : l'École du village, le Lycée militaire, l'Université de la capitale	École religieuse, École professionnelle, École à l'étranger	Un seul niveau de scolarité de 3 à 18 ans
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre le système éducatif	Quelles sont les obligations des parents d'élèves ?	Scolariser l'enfant (ou assurer l'instruction en famille) et respecter le règlement intérieur de l'école.	Les parents doivent enseigner la religion à l'école	Les parents peuvent contester tous les enseignements qui ne correspondent pas à leurs croyances	Les parents doivent payer les professeurs de l'école publique
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : liberté	Que dit l'article 4 de la Déclaration des droits de l'homme et du citoyen (1789) sur la liberté ?	« La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui » (art. 4 de la DDHC, 1789).	« La liberté est un droit réservé aux seuls citoyens nés en France »	« La liberté s'arrête là où commence l'autorité de l'État »	« La liberté est absolue et ne connaît aucune limite »
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre la devise française : égalité et fraternité	Depuis quand l'égalité entre les femmes et les hommes figure-t-elle dans la Constitution ?	Depuis 1946, dans le préambule de la Constitution.	Depuis 1789, dans la DDHC	Depuis 1958, dans la Constitution de la Ve République	Depuis 2004, dans la Charte de l'environnement
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Depuis quelle année le drapeau tricolore bleu, blanc, rouge est-il officiel ?	Depuis 1794.	Depuis 1789	Depuis 1830	Depuis 1958
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Qui a écrit La Marseillaise, et en quelle année ?	Rouget de Lisle, en 1792.	Victor Hugo, en 1830	Napoléon Bonaparte, en 1804	Beethoven, en 1804
Principes et valeurs de la République	Devise et symboles de la République	Connaître et comprendre les symboles républicains mentionnés par la Constitution et d'autres symboles coutumiers	Depuis quelle année la fête nationale du 14 juillet est-elle consacrée officiellement ?	Depuis 1880.	Depuis 1789	Depuis 1958	Depuis 1945
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quelle loi instaure la séparation des Églises et de l'État, et quel jour est-elle célébrée ?	La loi de 1905, célébrée chaque 9 décembre.	La loi de 1789, célébrée le 14 juillet	La loi de 1958, célébrée le 4 octobre	La loi de 1881, célébrée le 1er mai
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Le blasphème est-il un délit en France ?	Non, le blasphème n'est pas un délit en France.	Oui, il est puni d'une amende	Oui, il est puni d'une peine de prison	Cela dépend de la religion concernée
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Que prévoit la loi du 11 octobre 2010 ?	L'interdiction de dissimuler son visage dans l'espace public.	L'interdiction de tout signe religieux dans la rue	L'obligation du port du masque sanitaire	L'interdiction des manifestations religieuses publiques
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Que prévoit la loi du 15 mars 2004 ?	L'interdiction des signes religieux ostensibles à l'école publique.	L'interdiction de toute pratique religieuse en France	L'obligation d'enseigner une religion à l'école	L'interdiction des cantines scolaires confessionnelles
Principes et valeurs de la République	Laïcité	Connaître et comprendre le principe de laïcité	Quel territoire français ne suit pas le régime de séparation des Églises et de l'État de 1905 ?	L'Alsace-Moselle, qui garde un régime concordataire particulier.	La Corse	La Guadeloupe	Mayotte
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Que dit l'article 2 de la Constitution sur la démocratie ?	« Gouvernement du peuple, par le peuple et pour le peuple ».	« Le pouvoir appartient au président de la République »	« Le peuple délègue tous ses pouvoirs au Parlement »	« La démocratie est réservée aux élus »
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Combien de parrainages d'élus faut-il réunir pour se présenter à l'élection présidentielle ?	500 parrainages d'élus.	100 parrainages de citoyens	1000 parrainages de députés	Aucun parrainage n'est requis
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Combien de députés compte l'Assemblée nationale, et pour quelle durée sont-ils élus ?	577 députés, élus pour 5 ans au suffrage direct.	348 sénateurs, élus pour 6 ans	577 sénateurs, élus pour 9 ans	925 députés, élus pour 7 ans
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre les caractéristiques de notre démocratie	Combien de sénateurs compte le Sénat, et comment sont-ils élus ?	348 sénateurs, élus pour 6 ans au suffrage indirect.	577 sénateurs, élus au suffrage direct	348 députés, élus pour 5 ans	100 sénateurs, élus pour 3 ans
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre le droit de vote et les élections	Depuis quand le suffrage universel existe-t-il en France, et pour qui à l'origine ?	Depuis 1848, réservé aux hommes.	Depuis 1944, pour tous	Depuis 1789, pour les propriétaires	Depuis 1958, pour les hommes et les femmes
Le système institutionnel et politique	Démocratie et droit de vote	Connaître et comprendre le droit de vote et les élections	Quand les femmes ont-elles obtenu le droit de vote, et quand ont-elles voté pour la première fois ?	Droit de vote en 1944, premier vote en 1945.	Droit de vote en 1848, premier vote en 1852	Droit de vote en 1958, premier vote en 1965	Droit de vote en 1981, premier vote en 1988
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le découpage administratif et institutionnel	Combien de communes compte la France ?	34 875 communes (au 1er janvier 2025).	Environ 10 000 communes	101 communes	Environ 100 000 communes
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le découpage administratif et institutionnel	Combien de départements compte la France, et quel est le plus récent ?	101 départements ; le plus récent est Mayotte (2011).	96 départements ; le plus récent est la Corse	18 départements ; le plus récent est la Guyane	13 départements ; le plus récent est La Réunion
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le découpage administratif et institutionnel	Combien de régions compte la France ?	18 régions (13 en métropole et 5 en outre-mer).	22 régions, toutes en métropole	27 régions, comme les États membres de l'UE	5 régions, toutes en outre-mer
Le système institutionnel et politique	Organisation de la République française	Connaître et comprendre le découpage administratif et institutionnel	Qui représente l'État dans les départements et les régions ?	Les préfets.	Les maires	Les sénateurs	Les juges
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaître et comprendre les fondements de l'Union européenne	Quelles sont les grandes étapes de la construction européenne ?	CECA (1951), traité de Rome/CEE (1957), traité de Maastricht et création de l'UE (1992).	Traité de Versailles (1919), SDN (1920), ONU (1945)	Congrès de Vienne (1815), Sainte-Alliance (1815)	Accords de Schengen (1985) uniquement
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaître et comprendre les fondements de l'Union européenne	Quand le Royaume-Uni a-t-il quitté l'Union européenne (Brexit) ?	En 2020.	En 1992	En 2016	En 2002
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaître et comprendre les fondements de l'Union européenne	Depuis quand l'euro est-il en circulation, et combien de pays le partagent ?	Depuis 2002, partagé par 20 pays.	Depuis 1992, partagé par les 27 pays membres	Depuis 1957, partagé par tous les pays membres	Depuis 2020, partagé par 15 pays
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaitre et comprendre le fonctionnement de l'Union européenne	Où siège le Parlement européen, et quelle est la devise de l'Union européenne ?	À Strasbourg ; devise « Unie dans la diversité ».	À Bruxelles ; devise « Liberté, Égalité, Fraternité »	À Paris ; l'UE n'a pas de devise officielle	À Berlin ; devise « In varietate concordia » abandonnée en 2020
Le système institutionnel et politique	L'Union européenne et ses institutions	Connaitre et comprendre le fonctionnement de l'Union européenne	Que commémore la Journée de l'Europe, le 9 mai ?	La déclaration de Robert Schuman (1950).	La signature du traité de Rome (1957)	La chute du Mur de Berlin (1989)	La création de l'euro (2002)
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Depuis quand l'IVG est-elle garantie par la Constitution française ?	Depuis le 8 mars 2024.	Depuis 1975 (loi Veil)	Depuis 2013	Elle n'est pas inscrite dans la Constitution
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Depuis quand la PMA est-elle ouverte à toutes les femmes, et qu'en est-il de la GPA ?	PMA ouverte depuis la loi du 2 août 2021 ; la GPA reste interdite.	PMA et GPA sont toutes deux autorisées depuis 2021	PMA interdite, GPA autorisée depuis 2021	PMA et GPA sont interdites en France
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Quelle institution, créée en 2011, protège les droits des citoyens face aux administrations ?	Le Défenseur des droits.	Le Conseil constitutionnel	La Cour de cassation	Le Médiateur de la République (toujours en fonction)
Droits et devoirs	Droits fondamentaux	Connaitre les droits fondamentaux et leurs fondements	Quelle loi fonde la liberté d'association en France ?	La loi du 1er juillet 1901.	La loi de 1905	La loi de 1881 sur la presse	La Constitution de 1958
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Le vote est-il une obligation légale en France ?	Non, c'est un devoir civique mais pas une obligation légale.	Oui, sous peine d'amende	Oui, sous peine de prison	Oui, mais seulement pour les élections présidentielles
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Le service militaire obligatoire existe-t-il encore en France ?	Non, supprimé depuis 1997 ; remplacé par la JDC et, depuis le 1er janvier 2026, le service militaire volontaire (SMV, 8 mois, 18-25 ans).	Oui, il est obligatoire pour tous les jeunes de 18 ans	Non, et rien ne l'a jamais remplacé	Oui, mais seulement pour les femmes
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Quelles sont les trois catégories d'infractions en droit français, de la moins à la plus grave ?	Contraventions, délits, crimes.	Amendes, sanctions, condamnations	Fautes civiles, fautes pénales, fautes administratives	Infractions mineures, majeures, capitales
Droits et devoirs	Obligations et devoirs des personnes résidant en France	Comprendre les obligations et devoirs des personnes résidant en France	Quel tribunal juge les délits, et quelle peine maximale encourent-ils ?	Le tribunal correctionnel ; amende à partir de 3 750 € et jusqu'à 10 ans de prison.	La cour d'assises ; perpétuité	Le tribunal de police ; amende uniquement, sans prison	Le Conseil constitutionnel ; aucune peine
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Qui a proclamé l'abolition de l'esclavage en 1848, sous quelle République ?	Victor Schoelcher, sous la IIe République.	Napoléon Bonaparte, sous le 1er Empire	Jules Ferry, sous la IIIe République	Victor Hugo, sous la Restauration
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Quand l'école devient-elle gratuite, laïque et obligatoire, et sous l'impulsion de qui ?	Gratuite en 1881, laïque et obligatoire en 1882, sous Jules Ferry (IIIe République).	En 1789, sous la Révolution	En 1958, sous la Ve République	En 1945, sous le GPRF
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Quelle loi reconnaît l'esclavage comme crime contre l'humanité, et quand commémore-t-on son abolition ?	La loi Taubira (2001) ; commémoration le 10 mai.	La loi Veil (1975) ; commémoration le 8 mars	La loi de 1848 ; commémoration le 14 juillet	La loi de 1905 ; commémoration le 9 décembre
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Qui a fait abaisser la majorité civile à 18 ans, et en quelle année ?	Valéry Giscard d'Estaing, en 1974.	Charles de Gaulle, en 1958	François Mitterrand, en 1981	Jacques Chirac, en 1995
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Quelle loi dépénalise l'avortement en France, et qui la porte ?	La loi Veil, en 1975.	La loi Taubira, en 2001	La loi Badinter, en 1981	La loi de 1945 sur la Sécurité sociale
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Qui a fait abolir la peine de mort en France, et en quelle année ?	Robert Badinter, en 1981.	Simone Veil, en 1975	Valéry Giscard d'Estaing, en 1974	Charles de Gaulle, en 1958
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Qui a porté la loi ouvrant le mariage pour tous, et en quelle année ?	Christiane Taubira, en 2013.	Simone Veil, en 1975	Robert Badinter, en 1981	Élisabeth Guigou, en 1998
Histoire, géographie et culture	Principales périodes et personnages historiques	Connaître les repères historiques	Dans quel ordre se sont succédé les présidents de la Ve République, de de Gaulle à Macron ?	de Gaulle, Pompidou, Giscard d'Estaing, Mitterrand, Chirac, Sarkozy, Hollande, Macron.	de Gaulle, Mitterrand, Pompidou, Chirac, Giscard d'Estaing, Hollande, Sarkozy, Macron	Pompidou, de Gaulle, Chirac, Giscard d'Estaing, Sarkozy, Mitterrand, Macron, Hollande	de Gaulle, Chirac, Mitterrand, Giscard d'Estaing, Pompidou, Hollande, Sarkozy, Macron
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Quelle est la superficie de la France, et sa population en 2025 ?	Environ 675 000 km² pour 68,6 millions d'habitants.	Environ 1 million de km² pour 100 millions d'habitants	Environ 550 000 km² pour 50 millions d'habitants	Environ 675 000 km² pour 30 millions d'habitants
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Combien de pays frontaliers la France métropolitaine compte-t-elle ?	8 : Allemagne, Andorre, Belgique, Espagne, Italie, Luxembourg, Monaco, Suisse.	5, uniquement des pays de l'Union européenne	12, en comptant les territoires d'outre-mer	3 : Allemagne, Espagne, Italie
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Quel est le statut de la France au Conseil de sécurité de l'ONU ?	Membre permanent, avec un droit de veto.	Membre non permanent, sans droit de veto	Membre observateur uniquement	La France ne siège pas au Conseil de sécurité
Histoire, géographie et culture	Territoires et géographie	Connaître la situation geographique et demographique	Quel est le point culminant de la France, et son plus long fleuve ?	Le Mont-Blanc (4 810 m) ; la Loire est le plus long fleuve.	Le Mont-Blanc ; le Rhône est le plus long fleuve	Le Puy de Dôme ; la Seine est le plus long fleuve	Le Mont-Blanc ; le Rhin est le plus long fleuve
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	En quelle année le musée du Louvre a-t-il ouvert, et quelle œuvre célèbre y est exposée ?	1793 ; il abrite notamment La Joconde.	1889 ; il abrite la Tour Eiffel	1905 ; il abrite les impressionnistes	1958 ; il abrite le Code civil
Histoire, géographie et culture	Patrimoine français	Connaître les repères culturels de la société française	Combien de médailles la France a-t-elle remportées aux Jeux Olympiques et Paralympiques de Paris 2024 ?	64 médailles olympiques et 74 paralympiques.	100 médailles olympiques et 50 paralympiques	27 médailles olympiques, aucune paralympique	10 médailles olympiques et 10 paralympiques
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	À partir de quel taux d'alcoolémie la conduite devient-elle un délit en France ?	À partir de 0,8 g/l de sang.	À partir de 0,2 g/l	À partir de 1,5 g/l	L'alcool au volant n'est jamais un délit, seulement une contravention
Vivre dans la société française	S'installer et résider en France	Connaître les démarches essentielles pour garantir son installation et sa résidence dans le respect de la loi	Depuis le 1er juillet 2025, où le tabac est-il également interdit, en plus des lieux publics fermés ?	Dans les parcs, les plages de baignade, les abribus, et aux abords des écoles et des bibliothèques.	Uniquement dans les bureaux de tabac	Le tabac n'est interdit nulle part en extérieur	Uniquement dans les gares
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	En quelle année la Sécurité sociale a-t-elle été créée ?	En 1945.	En 1905	En 1958	En 1981
Vivre dans la société française	L'accès aux soins	Connaître le parcours de santé	Quel document permet d'être remboursé par l'Assurance Maladie ?	La carte Vitale.	La carte grise	La carte d'identité	Le livret de famille
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Quelle est la durée légale du travail en France, et comment s'appelle le salaire minimum ?	35 heures par semaine ; le salaire minimum est le SMIC.	39 heures par semaine ; le salaire minimum est le SMAG	40 heures par semaine ; il n'y a pas de salaire minimum légal	35 heures par semaine ; le salaire minimum est fixé par chaque entreprise
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Quel organisme accompagne la recherche d'emploi et verse les allocations chômage ?	France Travail, qui verse l'allocation ARE.	La CPAM	L'URSSAF	La CAF
Vivre dans la société française	Travailler en France	Connaître et comprendre les principales notions du droit du travail	Quel tribunal juge les litiges entre employeurs et salariés ?	Le conseil de prud'hommes.	Le tribunal correctionnel	Le tribunal de police	La cour d'assises
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre la vie familiale	Depuis quand le mariage pour tous existe-t-il en France, et quel rang mondial cela représente-t-il ?	Depuis le 17 mai 2013 ; la France est le 14e pays au monde à l'autoriser.	Depuis 1975 ; 1er pays au monde	Depuis 2004 ; 5e pays au monde	Depuis 2021 ; dernier pays européen à l'autoriser
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre la vie familiale	Quelle est la durée du congé paternité, et quelle nouveauté existe depuis le 1er janvier 2026 ?	28 jours de congé paternité ; un congé supplémentaire de naissance (1 à 2 mois) pour les enfants nés ou adoptés depuis 2026.	3 jours de congé paternité, sans évolution récente	16 semaines de congé paternité, comme le congé maternité	28 jours, supprimés depuis 2026
Vivre dans la société française	Autorité parentale et système éducatif	Connaître et comprendre la vie familiale	Depuis quelle loi la majorité numérique est-elle fixée à 15 ans en France ?	Depuis la loi du 7 juillet 2023 ; en dessous, l'inscription sur les réseaux sociaux nécessite l'accord d'un parent.	Depuis la loi de 2004 sur les signes religieux	Depuis la loi du 1er juillet 1901	Il n'existe pas de majorité numérique en France
Ma commune (fiche locale)	Élus et organisation de Paris	Connaître ses élus locaux (fiche personnelle, à jour après les municipales de mars 2026)	Qui est le maire du 19e arrondissement de Paris ?	François Dagnaud, maire du 19e depuis 2013, réélu le 6 avril 2026.	Emmanuel Grégoire	Anne Hidalgo	Valérie Pécresse
Ma commune (fiche locale)	Élus et organisation de Paris	Connaître ses élus locaux (fiche personnelle, à jour après les municipales de mars 2026)	Qui est le maire de Paris depuis les élections municipales de mars 2026 ?	Emmanuel Grégoire (PS), élu le 29 mars 2026, succède à Anne Hidalgo.	François Dagnaud	Anne Hidalgo	Valérie Pécresse
Ma commune (fiche locale)	Élus et organisation de Paris	Connaître ses élus locaux (fiche personnelle, à jour après les municipales de mars 2026)	Qui préside la Région Île-de-France ?	Valérie Pécresse, depuis 2015, réélue en 2021.	Emmanuel Grégoire	François Dagnaud	Emmanuel Macron
Ma commune (fiche locale)	Élus et organisation de Paris	Connaître ses élus locaux (fiche personnelle, à jour après les municipales de mars 2026)	Pourquoi Paris a-t-elle un statut particulier avec deux niveaux de maire ?	Paris est à la fois une commune et un département (75), en région Île-de-France.	Paris est uniquement une région	Paris n'a qu'un seul maire, comme toutes les communes	Paris est un territoire d'outre-mer
Ma commune (fiche locale)	Élus et organisation de Paris	Connaître ses élus locaux (fiche personnelle, à jour après les municipales de mars 2026)	Comment le maire de Paris est-il élu ?	Indirectement : les Parisiens élisent les conseillers de Paris, qui élisent ensuite le maire.	Au suffrage universel direct, comme le président de la République	Par le Premier ministre	Par tirage au sort parmi les conseillers d'arrondissement
Ma commune (fiche locale)	Élus et organisation de Paris	Connaître ses élus locaux (fiche personnelle, à jour après les municipales de mars 2026)	Depuis la loi du 11 août 2025, comment les Parisiens votent-ils aux élections municipales ?	Avec deux bulletins distincts et simultanés : un pour le Conseil de Paris, un pour le conseil d'arrondissement.	Avec un seul bulletin pour les deux conseils	Par vote électronique uniquement	Ils ne votent que pour le conseil d'arrondissement
Ma commune (fiche locale)	Élus et organisation de Paris	Connaître ses élus locaux (fiche personnelle, à jour après les municipales de mars 2026)	Que gère la mairie du 19e arrondissement, par opposition à la mairie de Paris ?	La proximité : état civil, inscriptions scolaires, équipements de quartier, vie associative locale.	Le budget et l'urbanisme de toute la ville	La police municipale de Paris	Les grandes décisions concernant tout Paris`;

  questions: Array<{ question: string; answer: string; thematique?: string; notions?: string; distractors?: string[] }> = [];
  @Input() maxQuestions?: number | null;
  pool: string[] = [];
  current = 0;
  correctCount = 0;
  incorrectCount = 0;
  choices: string[] = [];
  selected: string | null = null;
  finished = false;

  ngOnInit(): void {
    this.questions = this.parseTsv(this.rawTsv);
    this.pool = this.buildOptionsPool(this.questions);
    this.shuffle(this.questions);
    // If maxQuestions specified, select that many random questions
    if (this.maxQuestions && this.maxQuestions > 0 && this.questions.length > this.maxQuestions) {
      this.questions = this.questions.slice(0, this.maxQuestions);
      this.shuffle(this.questions);
    }
    if (this.questions.length) this.renderQuestion();
  }

  private parseTsv(tsv: string) {
    const lines = (tsv || '').split(/\r?\n/).map(l => l.trim()).filter(l => l.length > 0);
    if (lines.length <= 1) return [];
    const header = lines[0].split('\t').map(h => h.trim());
    const qIndex = header.findIndex(h => /question/i.test(h));
    const aIndex = header.findIndex(h => /reponse|réponse|answer/i.test(h));
    const themIndex = header.findIndex(h => /th[eé]matique|thematique/i.test(h));
    const notionsIndex = header.findIndex(h => /notion/i.test(h));
    // find distractor columns (accept English and French variants, or any header containing 'distract' or 'option')
    const distractorIndexes = header
      .map((h, idx) => ({ h, idx }))
      .filter(x => /distract|option/i.test(x.h))
      .map(x => x.idx);

    const items: Array<{question:string, answer:string, thematique?: string, notions?: string, distractors?: string[]}> = [];
    for (let i = 1; i < lines.length; i++) {
      const cols = lines[i].split('\t');
      const q = (cols[qIndex] || cols[3] || '').trim();
      const a = (cols[aIndex] || cols[4] || '').trim();
      const t = (cols[themIndex] || cols[0] || '').trim();
      const n = (cols[notionsIndex] || cols[1] || '').trim();
      const distractors = distractorIndexes.map(ix => (cols[ix] || '').trim()).filter(Boolean);
      if (q && a) items.push({ question: q, answer: a, thematique: t, notions: n, distractors: distractors.length ? distractors : undefined });
    }
    return items;
  }

  private buildOptionsPool(questions: Array<{question:string,answer:string}>) {
    return questions.map(q => q.answer).filter(Boolean);
  }

  private shuffle<T>(arr: T[]) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
  }

  private makeChoicesFor(index: number) {
    const q = this.questions[index];
    const correct = q.answer;
    // Use only the distractors provided for this question (do not mix answers from other questions).
    // If the TSV provides fewer than 3 distractors, we'll show only the provided ones plus the correct answer.
    const distractors: string[] = (q.distractors || []).map(d => d.trim()).filter(d => d && d !== correct);
    const opts = [correct, ...distractors];
    this.shuffle(opts);
    return opts;
  }

  renderQuestion() {
    if (!this.questions.length) return;
    this.choices = this.makeChoicesFor(this.current);
    this.selected = null;
    this.finished = false;
  }

  // progress percentage for the question accent bar (0-100)
  get progressPercent(): number {
    const total = this.questions.length || 1;
    if (this.finished) return 100;
    if (total <= 1) return 100;
    // use current index as progress; shows 0% at first question and 100% at last
    const pct = Math.round((this.current / (total - 1)) * 100);
    return Math.max(0, Math.min(100, pct));
  }

  selectOption(option: string) {
    if (this.selected) return; // already selected
    this.selected = option;
    const correct = this.questions[this.current].answer;
    if (option === correct) {
      this.correctCount++;
    } else {
      this.incorrectCount++;
    }
  }

  next() {
    if (this.current >= this.questions.length - 1) {
      this.finished = true;
      return;
    }
    this.current++;
    this.renderQuestion();
  }

  restart() {
    this.correctCount = 0;
    this.incorrectCount = 0;
    this.current = 0;
    this.shuffle(this.questions);
    this.renderQuestion();
  }
}